### ISSUE TITLE
Export on mac doesn't work.

### ISSUE THREAD

**Issue by cgeadas** [Xrayez/godot-imagetools#2]
**Module version:**

latest

**OS/device including version:**

macos Catalina 10.15.4

**Issue description:**

Project exported to macos using Imagetools don't work. Running it within Godot IDE works.
The error log is:
```
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: Intel Iris OpenGL Engine
 
Registered camera FaceTime HD Camera with id 1 position 0 at index 0
SCRIPT ERROR: GDScript::load_byte_code: Parse Error: The identifier "ImageIndexed" isn't declared in the current scope.
   At: res://TurzzleTool.gdc:41.
ERROR: load_byte_code: Method failed. Returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:778.
ERROR: load: Cannot load byte code from file 'res://TurzzleTool.gdc'.
   At: modules/gdscript/gdscript.cpp:2240.
ERROR: _load: Failed loading resource: res://TurzzleTool.gdc.
   At: core/io/resource_loader.cpp:278.
ERROR: poll: res://TurzzleTool.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://TurzzleTool.gd
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Failed to load resource 'res://TurzzleTool.tscn'.
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://TurzzleTool.tscn.
   At: core/io/resource_loader.cpp:278.
ERROR: start: Failed loading scene: res://TurzzleTool.tscn
   At: main/main.cpp:1864.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2071.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:476.

```

Is there any procedure for export when using this module?
Any values/flags that need to be set?

**Comment by Xrayez** [comment]
> Project exported to macos using Imagetools don't work. Running it within Godot IDE works.

Make sure you actually compile export templates as well. Something like:
```
scons platform=osx target=release tools=no
```

See [Windows-specific export instructions](https://docs.godotengine.org/en/3.2/development/compiling/compiling_for_windows.html#creating-windows-export-templates) because the [macOS page](https://docs.godotengine.org/en/3.2/development/compiling/compiling_for_osx.html) doesn't seem to contain this information...

**Comment by cgeadas** [comment]
Thank you Andrii. I had completely forgotten the need to build also custom export templates.
The macOS process is not simple, it justifies detailed instructions. Gladly I've found this:
https://www.reddit.com/r/godot/comments/9xblzl/how_do_i_generate_an_export_template_for_my/

During compiling I've got this warning:
```
modules/imagetools/drivers/png/image_loader_indexed_png.cpp:261:13: warning: unused function '_write_png_data'
      [-Wunused-function]
static void _write_png_data(png_structp png_ptr, png_bytep data, png_size_t p_length) {
            ^
1 warning generated.
```
